### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by cyacedev** [ViewTube/viewtube-vue#127]
### description
Due to the new addition of TypeScript to the client-side, it would be best to start migrate all current code to typescript if applicable.

### acceptance criterias
- [x] migrated to TypeScript
- [x] migrate all components
- [x] migrate all pages
- [x] migrate all plugins
- [x] migrate all directives
- [x] If possible, no new issues from deepscan

### Subissues
~#129 Store Migration~ ✅
